(function() {
  'use strict';

  angular
    .module('marketplace')
    .factory('UsersMockFacltory', UsersMockFacltory);

    UsersMockFacltory.$inject = [];

    function UsersMockFacltory() {
      var mockUsers =[
        {
            name: 'Obiwan',
            surname: 'Kenovi',
            company: 'Fundació I2cat',
            jobPosition: 'Developer',
            providerRole: true,
            clientRole: false,
            phone: 623456711,
            activated: true,
            address: 'Diagonal, 327',
            mail: 'david@i2cat.net',
            city: 'Barcelona',
            country: 'Espanya',
            cp: 08123,
            description: 'Software Developer at I2cat',
            legal: false
        },
        {
            name: 'Capità',
            surname: 'Enciam',
            company: 'Fundació I2cat',
            jobPosition: 'Developer',
            providerRole: false,
            clientRole: true,
            phone: 639786599,
            activated: false,
            address: 'Valencia, 223',
            mail: 'enciam@i2cat.net',
            city: 'Barcelona',
            country: 'Espanya',
            cp: 08080,
            description: 'Software Engineer at I2cat',
            legal: false
        },
        {
            name: 'Joan',
            surname: 'Fontpineda',
            company: 'Cloud Systems',
            jobPosition: 'Product Manager',
            providerRole: false,
            clientRole: true,
            phone: 639567122,
            activated: true,
            address: 'Aragó 234',
            mail: 'fontpineda@cloudsystems.cat',
            city: 'Barcelona',
            country: 'França',
            cp: 08041,
            description: 'Product Manager at I2cat',
            legal: true
        },
        {
            name: '6666666',
            surname: 'zzzzzzz',
            company: 'Fundació I2cat',
            jobPosition: 'Developer',
            providerRole: true,
            clientRole: false,
            phone: 623456711,
            activated: true,
            address: 'Diagonal, 327',
            mail: 'david@i2cat.net',
            city: 'Barcelona',
            country: 'Espanya',
            cp: 08123,
            description: 'Software Developer at I2cat',
            legal: false
        },
        {
            name: 'cccccc',
            surname: 'xxxxxxx',
            company: 'Fundació I2cat',
            jobPosition: 'Developer',
            providerRole: false,
            clientRole: true,
            phone: 639786599,
            activated: false,
            address: 'Valencia, 223',
            mail: 'enciam@i2cat.net',
            city: 'Barcelona',
            country: 'Espanya',
            cp: 08080,
            description: 'Software Engineer at I2cat',
            legal: false
        },
        {
            name: 'xxxxx',
            surname: 'kkkkkkkkk',
            company: 'Cloud Systems',
            jobPosition: 'Product Manager',
            providerRole: false,
            clientRole: true,
            phone: 639567122,
            activated: true,
            address: 'Aragó 234',
            mail: 'fontpineda@cloudsystems.cat',
            city: 'Barcelona',
            country: 'França',
            cp: 08041,
            description: 'Product Manager at I2cat',
            legal: true
        },
        {
            name: '1111221212121',
            surname: 'rtrtrtrtrtr',
            company: 'Fundació I2cat',
            jobPosition: 'Developer',
            providerRole: true,
            clientRole: false,
            phone: 623456711,
            activated: true,
            address: 'Diagonal, 327',
            mail: 'david@i2cat.net',
            city: 'Barcelona',
            country: 'Espanya',
            cp: 08123,
            description: 'Software Developer at I2cat',
            legal: false
        },
        {
            name: '34543534556456',
            surname: 'fhgfhrthrth',
            company: 'Fundació I2cat',
            jobPosition: 'Developer',
            providerRole: false,
            clientRole: true,
            phone: 639786599,
            activated: false,
            address: 'Valencia, 223',
            mail: 'enciam@i2cat.net',
            city: 'Barcelona',
            country: 'Espanya',
            cp: 08080,
            description: 'Software Engineer at I2cat',
            legal: false
        },
        {
            name: '0p0p0p0p0p0p0p',
            surname: 'nmnmnmnmnmmn',
            company: 'Cloud Systems',
            jobPosition: 'Product Manager',
            providerRole: false,
            clientRole: true,
            phone: 639567122,
            activated: true,
            address: 'Aragó 234',
            mail: 'fontpineda@cloudsystems.cat',
            city: 'Barcelona',
            country: 'França',
            cp: 08041,
            description: 'Product Manager at I2cat',
            legal: true
        },
        {
            name: 'fvfvfvfvfvfvf',
            surname: 'ikiikikiki',
            company: 'Fundació I2cat',
            jobPosition: 'Developer',
            providerRole: true,
            clientRole: false,
            phone: 623456711,
            activated: true,
            address: 'Diagonal, 327',
            mail: 'david@i2cat.net',
            city: 'Barcelona',
            country: 'Espanya',
            cp: 08123,
            description: 'Software Developer at I2cat',
            legal: false
        },
        {
            name: '1212121212',
            surname: '565656565656',
            company: 'Fundació I2cat',
            jobPosition: 'Developer',
            providerRole: false,
            clientRole: true,
            phone: 639786599,
            activated: false,
            address: 'Valencia, 223',
            mail: 'enciam@i2cat.net',
            city: 'Barcelona',
            country: 'Espanya',
            cp: 08080,
            description: 'Software Engineer at I2cat',
            legal: false
        },
        {
            name: 'azzaazazaz',
            surname: 'axaxaxaxaax',
            company: 'Cloud Systems',
            jobPosition: 'Product Manager',
            providerRole: false,
            clientRole: true,
            phone: 639567122,
            activated: true,
            address: 'Aragó 234',
            mail: 'fontpineda@cloudsystems.cat',
            city: 'Barcelona',
            country: 'França',
            cp: 08041,
            description: 'Product Manager at I2cat',
            legal: true
        },
        {
            name: 'Obiwan',
            surname: 'Kenovi',
            company: 'Fundació I2cat',
            jobPosition: 'Developer',
            providerRole: true,
            clientRole: false,
            phone: 623456711,
            activated: true,
            address: 'Diagonal, 327',
            mail: 'david@i2cat.net',
            city: 'Barcelona',
            country: 'Espanya',
            cp: 08123,
            description: 'Software Developer at I2cat',
            legal: false
        },
        {
            name: 'Capità',
            surname: 'Enciam',
            company: 'Fundació I2cat',
            jobPosition: 'Developer',
            providerRole: false,
            clientRole: true,
            phone: 639786599,
            activated: false,
            address: 'Valencia, 223',
            mail: 'enciam@i2cat.net',
            city: 'Barcelona',
            country: 'Espanya',
            cp: 08080,
            description: 'Software Engineer at I2cat',
            legal: false
        },
        {
            name: 'Joan',
            surname: 'Fontpineda',
            company: 'Cloud Systems',
            jobPosition: 'Product Manager',
            providerRole: false,
            clientRole: true,
            phone: 639567122,
            activated: true,
            address: 'Aragó 234',
            mail: 'fontpineda@cloudsystems.cat',
            city: 'Barcelona',
            country: 'França',
            cp: 08041,
            description: 'Product Manager at I2cat',
            legal: true
        },
        {
            name: '6666666',
            surname: 'zzzzzzz',
            company: 'Fundació I2cat',
            jobPosition: 'Developer',
            providerRole: true,
            clientRole: false,
            phone: 623456711,
            activated: true,
            address: 'Diagonal, 327',
            mail: 'david@i2cat.net',
            city: 'Barcelona',
            country: 'Espanya',
            cp: 08123,
            description: 'Software Developer at I2cat',
            legal: false
        },
        {
            name: 'cccccc',
            surname: 'xxxxxxx',
            company: 'Fundació I2cat',
            jobPosition: 'Developer',
            providerRole: false,
            clientRole: true,
            phone: 639786599,
            activated: false,
            address: 'Valencia, 223',
            mail: 'enciam@i2cat.net',
            city: 'Barcelona',
            country: 'Espanya',
            cp: 08080,
            description: 'Software Engineer at I2cat',
            legal: false
        },
        {
            name: 'xxxxx',
            surname: 'kkkkkkkkk',
            company: 'Cloud Systems',
            jobPosition: 'Product Manager',
            providerRole: false,
            clientRole: true,
            phone: 639567122,
            activated: true,
            address: 'Aragó 234',
            mail: 'fontpineda@cloudsystems.cat',
            city: 'Barcelona',
            country: 'França',
            cp: 08041,
            description: 'Product Manager at I2cat',
            legal: true
        },
        {
            name: '1111221212121',
            surname: 'rtrtrtrtrtr',
            company: 'Fundació I2cat',
            jobPosition: 'Developer',
            providerRole: true,
            clientRole: false,
            phone: 623456711,
            activated: true,
            address: 'Diagonal, 327',
            mail: 'david@i2cat.net',
            city: 'Barcelona',
            country: 'Espanya',
            cp: 08123,
            description: 'Software Developer at I2cat',
            legal: false
        },
        {
            name: '34543534556456',
            surname: 'fhgfhrthrth',
            company: 'Fundació I2cat',
            jobPosition: 'Developer',
            providerRole: false,
            clientRole: true,
            phone: 639786599,
            activated: false,
            address: 'Valencia, 223',
            mail: 'enciam@i2cat.net',
            city: 'Barcelona',
            country: 'Espanya',
            cp: 08080,
            description: 'Software Engineer at I2cat',
            legal: false
        },
        {
            name: '0p0p0p0p0p0p0p',
            surname: 'nmnmnmnmnmmn',
            company: 'Cloud Systems',
            jobPosition: 'Product Manager',
            providerRole: false,
            clientRole: true,
            phone: 639567122,
            activated: true,
            address: 'Aragó 234',
            mail: 'fontpineda@cloudsystems.cat',
            city: 'Barcelona',
            country: 'França',
            cp: 08041,
            description: 'Product Manager at I2cat',
            legal: true
        },
        {
            name: 'fvfvfvfvfvfvf',
            surname: 'ikiikikiki',
            company: 'Fundació I2cat',
            jobPosition: 'Developer',
            providerRole: true,
            clientRole: false,
            phone: 623456711,
            activated: true,
            address: 'Diagonal, 327',
            mail: 'david@i2cat.net',
            city: 'Barcelona',
            country: 'Espanya',
            cp: 08123,
            description: 'Software Developer at I2cat',
            legal: false
        },
        {
            name: '1212121212',
            surname: '565656565656',
            company: 'Fundació I2cat',
            jobPosition: 'Developer',
            providerRole: false,
            clientRole: true,
            phone: 639786599,
            activated: false,
            address: 'Valencia, 223',
            mail: 'enciam@i2cat.net',
            city: 'Barcelona',
            country: 'Espanya',
            cp: 08080,
            description: 'Software Engineer at I2cat',
            legal: false
        },
        {
            name: 'azzaazazaz',
            surname: 'axaxaxaxaax',
            company: 'Cloud Systems',
            jobPosition: 'Product Manager',
            providerRole: false,
            clientRole: true,
            phone: 639567122,
            activated: true,
            address: 'Aragó 234',
            mail: 'fontpineda@cloudsystems.cat',
            city: 'Barcelona',
            country: 'França',
            cp: 08041,
            description: 'Product Manager at I2cat',
            legal: true
        }
      ];

      return mockUsers;

    }
})();
